#################################
#####          速度         #####
#################################
#短期检测
short:
  clear: 3             #短期的清理(检测)间隔,单位秒,>=1
  #提示: 短期间隔可分为命令与非命令的检测
  #>如果是命令的间隔检测,则间隔过短时适合使用NCP自带的命令限制功能(如1,2级);间隔长时使用没有问题
  #>如果是非命令的检测(如玩家踩踏板触发事件的频率检测),则使用没有问题
  levels:                      #等级列表,从上到下为1,2,3...级
    - 250
    - 550
    - 1400

#侧边栏提示(需要前置插件Lib_msg)(可选)
side:
  enable: true                 #不开启或前置不满足则显示在聊天栏(在聊天栏显示时,不会强制显示,因此有界面时显示不出)
  clear: 1250                  #多少ms后清除提示,>=1

#语言
lang:
  cn: "lang_cn.yml"